# Generated by Django 4.2.2 on 2023-06-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie1',
            name='im',
            field=models.ImageField(default='fdccdv', upload_to='Gallery'),
            preserve_default=False,
        ),
    ]
